class Book {
  String title,
      writer,
      price,
      image,
      link,
      description;
  int pages;
  double rating,
      height;

  Book(
      this.title, this.writer, this.price, this.image, this.rating, this.pages, this.height, this.link, this.description);

  static List<Book> generateSemua() {
    return[
      Book('Android Application Development for Rookies with Database', 'Nadia Firly', 'Rp 70.000',
          'assets/images/rookies.jpg', 4.9, 264, 270, 'https://www.lazada.co.id/products/buku-android-application-development-for-rookies-with-database-i640790397-s890124392.html', 'Sudah tidak zaman lagi kebanyakan teori. Buku Android Application Development for Rookies with Database akan memandu Anda dalam melakukan berbagai implementasi program pada Android Studio. Dengan silabus yang tepat dan bahasa yang mudah dipahami, kini siapa pun bisa menjadi developer Android. Ayo bangun dan jadilah pemain! Sudah saatnya Anda membuat sebuah aplikasi hingga dapat mengunggahnya ke Google Play. Terlebih, proyek yang ada pada buku ini telah menggunakan 2 jenis database, yaitu SQLite dan Firebase sekaligus.'),
      Book('Fish in The Water', 'Lee Chanhyuk', 'Rp 63.000',
          'assets/images/fish.jpg', 4.9, 176, 270, 'https://www.tokopedia.com/gramedia-store/fish-in-the-water', 'Fish in the Water bertutur tentang kisah intens yang menjungkirbalikkan imajinasi, dengan komposisi kuat untuk menunjukkan pertentangan antara ambisi dan ketakutan,kebebasan dan kendali, kebahagiaan dari cinta dan luka dari kehilangan, serta arti kehidupan, terkadang dengan tenangdan terkadang dengan fantastis.'),
      Book('Detektif Conan The Movie: The Raven Chaser 01', 'Aoyama Gosho', 'Rp 40.000',
          'assets/images/conan.jpg', 5.0, 192, 270, 'https://www.lazada.co.id/products/detektif-conan-the-movie-the-raven-chaser-01-i5132828577-s9543452084.html', 'Terjadi pembunuhan berantai di mana pelaku meninggalkan sekeping pion mahjong di tkp. Tetapi, tampaknya ini lebih pelik dari sekedar pembunuhan, karena bayang-bayang organisasi hitam mulai muncul...!?'),
      Book('Sebuah Seni Untuk Bersikap Bodo Amat', 'Mark Manson', 'Rp 67.000',
          'assets/images/bodo.jpg', 4.9, 224, 270, 'https://www.tokopedia.com/gramedia-store/sebuah-seni-untuk-bersikap-bodo-amat', 'Dalam buku pengembangan diri yang mewakili generasi ini, seorang bloger superstar menunjukkan pada kita baa kunci untuk menjadi orang yang lebih kuat, lebih bahagia adalah dengan mengerjakan segala tantangan dengan lebih baik dan berhenti memaksa diri untuk menjadi "positif" di setiap saat. Selama beberapa tahun belakangan, Mark Manson-melalui blognya yang sangat populer-telah membantu mengoreksi harapan-harapan delusional kita, baik mengenai diri kita sendiri maupun dunia. Ia kini menuangkan buah pikirnya yang keren itu di dalam buku hebat ini. Manson melontarkan argumen baa manusia tak sempurna dan terbatas. Begini tulisnya, "tidak semua orang bisa menjadi luar biasa-ada para pemenang dan pecundang di masyarakat, dan beberapa di antaranya tidak adil dan bukan akibat kesalahan Anda." Manson mengajak kita untuk mengerti batasan-batasan diri dan menerimanya-baginya, ini adalah sumber kekuatan yang paling nyata. Tepat saat kita mampu mengakrabi ketakutan, kegagalan, dan ketidakpastian-tepat saat kita berhenti melarikan diri dan mengelak, dan mulai menghadapi kenyataan-kenyataan yang menyakitkan-saat itulah kita bisa mulai menemukan keberanian dan kepercayaan diri yang selama ini kita cari dengan sekuat tenaga. "Dalam hidup ini, kita hanya punya kepedulian dalam jumlah yang terbatas. Makanya, Anda harus bijaksana dalam menentukan kepedulian Anda." Manson menciptakan momen perbincangan yang serius dan mendalam, dibungkus dengan cerita-cerita yang menghibur dan "kekinian", serta humor yang cadas. Buku ini merupakan tamparan di wajah yang menyegarkan untuk kita semua, supaya kita bisa mulai menjalani kehidupan yang lebih memuaskan, dan apa adanya.'),
      Book('Otodidak Adobe After Effects dan Adobe Premiere', 'Jubilee Enterprise', 'Rp 74.000',
          'assets/images/after.jpg', 4.8, 284, 270, 'https://www.lazada.co.id/products/otodidak-adobe-after-effects-dan-adobe-premiere-i3057640443-s5426786772.html', 'Adobe Premiere Pro CC 2019 yang dibahas di dalam buku ini merupakan software paling bagus untuk mengedit video. Maka dari itu, pembahasan dasar-dasar video editing seperti mengimpor footage, mengelola clip, mengatur sequence dan timeline, membuat marker, menghadirkan efek-efek khusus, menulis teks, mengontrol audio, dan lain sebagainya, dibahas secara singkat tapi jelas.'),
      Book('Serangkai', 'Valerie Patkar', 'Rp 99.000',
          'assets/images/serangkai.jpg', 5.0, 404, 270, 'https://shopee.co.id/Serangkai-(karya-Valerie-Patkar)-i.63842097.8803955567', '“Tetapi bukan masalah kalau kita nggak selalu bisa berani, Deverra. Karena manusia bukan hanya lahir dari tulang, melainkan juga hati. Semesta bukan hanya menciptakan tubuh, melainkan juga rasa. Dan waktu bukan hanya tentang hari esok, melainkan juga kemarin.”. Kecelakaan di perhelatan Grand Prix Formula 1 membawa Kai Deverra yang masih merayakan penyesalan ditinggal kekasih lamanya kepada Karina Maladivas Nota yang baru pulang dari kesepian. Setangkai cerita kesedihan Deverra menyatu dengan setangkai cerita kesunyian Divas, membentuk serangkai cerita untuk mengenang yang hilang. Tentang Deverra, Dari Divas, untuk Zacchio.'),
      Book('Haikyu!!: Fly High! Volleyball! 24', 'Haruichi Furudate', 'Rp 28.000',
          'assets/images/haikyu.jpeg', 5.0, 216, 270, 'https://www.lazada.co.id/products/haikyu-fly-high-volleyball-21-i3057280513-s5426416273.html', 'Pertandingan melawan Shiratorizawa telah sampai pada set kelima. Cedera yang dialami Tsukishima menyebabkan kekosongan pada pilar pertahanan Karasuno, tapi mereka terus berjuang dengan tekad kuat untuk merebut angka! Pertarungan sengit yang menguras stamina ini akhirnya sampai pada babak terakhir. Siapakah yang akan mendapatkan predikat wakil prefektur?'),
      Book('The Power of Habit', 'Charles Duhigg', 'Rp 90.000',
          'assets/images/habit.jpg', 4.9, 371, 270, 'https://www.lazada.co.id/products/the-power-of-habit-i592650472-s836348894.html', '"Few (books) become essential manuals for businesa and living. The Power of Habit is an axception. Charles Duhigg not only explains how habits are formed but how to kock bad anes and hang on to the good"- Financial Times"You wll never look at yourself, your organization, or your world quite the same way." - DANIEL H. PINK, bestselling author of Drive and A Whole New Mind'),
      Book('Desain Web bagi Pemula', 'Candra Surya & Miftahul Jannah', 'Rp 70.000',
          'assets/images/desain.jpg', 4.9, 292, 270, 'https://www.tokopedia.com/gramedia-store/desain-web-bagi-pemula', 'Buku ini membahas cara merancang web menggunakan bahasa HTML dan CSS, menitikberatkan pada study kasus serta contoh penggunaan setiap kode HTML dan CSS. Dan masih banyak lagi pembahasan lainnya yang tidak kalah penting untuk dipelajari.'),
      Book('To Heal Is To Let Go', 'Adi K.', 'Rp 82.000',
          'assets/images/letgo.jpg', 4.7, 196, 270, 'https://www.tokopedia.com/gramedia-store/to-heal-is-to-let-go-to-heal-2-hc', 'Hidup adalah soal menerima dan melepaskan. Melepaskan sesuatu yang dulu pernah menjadi bagian terbaik dari hidupmu. Melepaskan beban dan masa lalu yang suram dan menyedihkan. Melepaskan kebencian dan dendam yang selama ini menghantui pikiranmu. Namun pada kenyataannya melepaskan tidak semudah yang diucapkan. Kadang sulit, bahkan sangat sulit. Kau harus benar-benar bisa melupakan dan merelakan untuk dapat melepaskan dengan sesungguh-sungguhnya. “To Heal is To Let Go” adalah buku self-motivation untuk remaja hingga dewasa yang sedang dilanda masalah dan kehilangan rasa percaya diri. Dengan nasihat-nasihat yang pendek, lugas, dan langsung, buku ini dapat menjadi inspirasi, penyemangat, serta penenang hati.'),
      Book('Jujutsu Kaisen 01', 'Gege Akutami', 'Rp 40.000',
          'assets/images/jujutsu.jpg', 5.0, 200, 270, 'https://www.lazada.co.id/products/jujutsu-kaisen-01-i4715126888-s8483282113.html', 'Yuji Itadori seorang murid SMA dengan kemampuan atletik yang luar biasa. Kesehariannya adalah menjenguk kakeknya yang terbaring di rumah sakit. Suatu hari, segel "objek terkutuk" yang berada di sekolahnya terlepas, monster-monster pun mulai bermunculan. Yuji menyusup ke dalam gedung sekolah demi menolong senior di klubnya, akan tetapi...!?'),
      Book('You Do You: Discovering Life through Experiments & Self Awareness', 'writer', 'Rp 128.000',
          'assets/images/you.jpg', 5.0, 252, 270, 'https://www.tokopedia.com/gramedia-store/you-do-you-discovering-life-through-experiments-self-awareness', '“Mas, gimana kalau passion gue belum menghasilkan?” “Mas, apakah lebih baik jadi generalis atau spesialis?” “Mas, gue pengin bisa ganti haluan karier di bidang yang lain, bisakah? “Mas, gue lagi di tengah-tengah quarter-life crisis. Help me.” “Mas, gue bingung ikigai gue apa.” “Mas, emang di usia 30 nanti, secara finansial gue udah mesti punya apa aja?” “Mas, berbagi dong proses lo menuju ke Rp1M pertama.” I feel you. Gue juga pernah mengalami keresahan yang sama. Faktanya, satu dekade pertama dalam perjalanan karier gue dihabiskan untuk bereksperimen dengan sembilan macam role yang berbeda, sampai akhirnya gue menemukan ikigai. Sales, petugas lelang, operator alat berat, travel blogger, food photographer, penyanyi, social media manager, product manager di sebuah tech startup, sampai pengusaha pernah gue jalani. Menariknya, semua kegalauan dan pencarian itu mulai terjawab dengan sendirinya ketika gue bisa menjawab pertanyaan: “Who are you?” Ketika gue mengenal diri sendiri, maka pada titik itulah gue menemukan jawaban bahwa “your life (career, business, relationship, and finance) should be an extension of who you are”. Buku ini nggak ngasih jawaban langsung, tapi ngebantu merefleksi diri, melihat ke dalam, mengurai situasi, supaya lo bisa menemukan sendiri jawaban, kapan pun lo bertemu dengan persimpangan. Let`s begin the journey of finding yourself.'),
      Book('7 in 1 Pemograman Web untuk Pemula', 'Rohi Abdulloh', 'Rp 74.800',
          'assets/images/pemula.jpg', 5.0, 338, 270, 'https://www.tokopedia.com/gramedia-store/7-in-1-pemrograman-web-untuk-pemula','Teknologi pemrograman web berkembang begitu cepat. Bagi pemula, tentu akan sangat tertinggal jika tidak cepat mengejarnya. Buku ini membahas 7 materi utama dalam mempelajari pemrograman web. Ketujuh bahasan ini akan sangat membantu pemula yang ingin menjadi web programmer dalam waktu yang singkat. Pembahasan dimulai dari pengetahuan dasar tentang pemrograman web, dilanjutkan dengan pembahasan 7 materi pemrograman web satu per satu disertai dengan contoh skrip beserta hasilnya.'),
      Book('Percakapan Paling Panjang Perihal Pulang Pergi', 'Theoresia Rumthe & Weslly Johannes', 'Rp 50.000',
          'assets/images/pergi.jpg', 4.9, 124, 270, 'https://www.tokopedia.com/gramedia-store/percakapan-paling-panjang-perihal-pulang-pergi', 'Bukan jalan yang membawa manusia sampai ke tujuan, melainkan sepasang kaki yang kuat.'),
      Book('One Piece 90', 'Eiichiro Oda', 'Rp 25.000',
          'assets/images/one.jpg', 4.9, 200, 270, 'https://www.lazada.co.id/products/one-piece-90-i1561334464-s2986694688.html', 'Bendera bajak laut Kelompok Topi Jerami mengambang di lautan... Apa mereka telah dikalahkan oleh gempuran kelompok Mom yang tak terhentikan!? Bagian WCI yang menegangkan mencapai akhir!! Dan cerita memasuki babak Levely di mana berbagai tujuan bercampur aduk!! Simak inilah kisah petualangan di lautan, One Piece!!'),
      Book('Semoga Kamu Baik-Baik Saja', 'Marcella Viona Legoh', 'Rp 85.000',
          'assets/images/baikbaik.jpg', 5.0, 128, 270, 'https://www.tokopedia.com/gramedia-store/semoga-kamu-baik-baik-saja-spesial-offer', 'Bahagia, capek,, galau, stres, bangga, sedih, kasmaran, takut, semangat, kesal, panik, pusing, penuh harapan, kecewa. Hidup pasti ada naik turunnya. Tapi dalam keadaan baik maupun buruk, selalu ada pesan-pesan kehidupan yang bisa membantu kita buat jadi lebih baik. Buku ini adalah pengingat bahwa apa yang sedang kita alami, hidup tetap bisa dinikmati, mumpung kita masih disini!'),
      Book('Membuat Sendiri Aplikasi Augmented Reality', 'Ani Ismayani', 'Rp 60.000',
          'assets/images/ar.jpg', 4.5, 228, 270, 'https://www.tokopedia.com/gramedia-store/membuat-sendiri-aplikasi-augmented-reality', 'Penggunaan AR sudah sangat umum, mulai dari game sampai dunia pendidikan dan pembelajaran. Tersedianya aplikasi gratis seperti Unity dan Vuforia memungkinkan pembuatan aplikasi berbasis AR tidak sulit dilakukan oleh siapa saja. Buku ini secara umum menjelaskan bagaimana pemanfaatan AR dalam pembelajaran. Di sini diberikan contoh pembuatan AR dalam bentuk bangun ruang sederhana, harimau 3D, dan video player atau animasi. Meskipun secara umum ditujukan untuk pembelajaran, langkah-langkah yang dijelaskan di sini tentu saja dapat diterapkan untuk aplikasi lainnya, misalnya membuat game 3D. Semua tergantung kreativitas Anda.'),
      Book('Tenang, Semua akan Baik-Baik Saja', 'Jedit', 'Rp 110.000',
          'assets/images/baik.jpg', 4.8, 244, 270, 'https://www.tokopedia.com/gramedia-store/tenang-semua-akan-baik-baik-saja', 'Aku menyiapkan kisah-kisah tentang perjalanan mencari kenangan indah, penantian terhadap sinar mentari pagi. Kisah yang akan menemani saat terjaga di tengah malam dan kisah yang akan diceritakan saat malam berbintang. Aku sangat senang jika kita bisa pergi ke semesta kecilku. Di sana, kita bisa berbagi cerita bersama. Mampirlah, aku selalu menunggu di sini.'),
      Book('Demon Slayer: Kimetsu No Yaiba 05', 'Koyoharu Gotouge', 'Rp 40.000',
          'assets/images/demon.jpg', 4.9, 192, 270, 'https://www.lazada.co.id/products/demon-slayer-kimetsu-no-yaiba-05-i4905384747-s9034450569.html', 'Tanjiro Dkk. akhirnya beranjak menuju Gunung Natagumo dan bertarung begitu alot melawan keluarga iblis laba-laba penghuni gunung tersebut! Zenitsu terkena racun yang akan mengubahnya menjadi laba-laba, Inosuke dan Tanjiro menjadi bulan-bulanan iblis raksasa yang berperan sebagai ayah. Ujung pertarungan mereka belum tampak... Di tengah keputusasaan itu, adakah yang bergerak menyusul mereka di belakang!?'),
      Book('Buku Antimalas dan Suka Menunda', 'Eya Agency', 'Rp 120.000',
          'assets/images/suka.jpg', 5.0, 250, 270, 'https://www.tokopedia.com/gramedia-store/buku-antimalas-dan-suka-menunda', 'Pernahkah kamu merasa sudah berjuang keras tetapi masih dianggap malas? Ada yang menghakimi kamu malas karena mendapat nilai jelek, padahal kamu sudah berlajar mati-matian. Ada yang menghakimi kamu malas karena target kerja tidak tercapai, padahal kamu sudah berhari-hari lembur untuk menyelesaikannya. Atau, kamu memang lebih suka rebahan? Nah, sebenarnya apakah kamu memang benar malas, atau ada hal lain yang membuatmu terlihat malas? Coba cari tahu melalui buku ini dan temukan solusinya. Karena sesungguhnya, ada kemalasan yang disebabkan oleh masalah emosi, sehingga perlu dicari tahu akar permasalahannya untuk membasmi rasa malas tersebut.'),
      Book('Paket Lengkap CorelDraw dan Photoshop', 'Alfa Hartoko', 'Rp 80.000',
          'assets/images/corel.jpg', 4.8, 304, 270, 'https://www.tokopedia.com/gramedia-store/paket-lengkap-coreldraw-dan-photoshop', 'Buku ini bisa menjadi solusi bagi Anda yang ingin mendapatkan pembahasan lengkap mengenai kinerja dua software grafis sekaligus, yaitu CorelDraw dan Photoshop. Secara komplet, buku ini mengulas seluruh langkah-langkah penggunaan fasilitas yang ada di CorelDraw dan Photoshop mulai dari dasar hingga Anda mampu untuk membuat kreasi dari kedua software grafis tersebut. Beragam fasilitas dalam CorelDraw dan Photoshop seperti penggunaan tool, pewarnaan, pencahayaan, pembuatan teks, teknik koreksi, serta pembuatan desain secara tuntas bisa didapat di buku ini. Editing Foto untuk menghasilkan efek yang sangat menarik diulas dalam buku ini secara gamblang dan padat. Bagi Anda yang ingin secara langsung masuk dunia kerja dan mendapatkan penghasilan dari software grafis juga bisa karena buku ini langsung mengajarkan cara membuat desain yang bernilai jual, seperti kreasi teks dan pengolahan, serta editing foto. Jadi, Anda tidak hanya diajari teori seputar penggunaan CorelDraw dan Photoshop namun juga langsung pada penerapannya.'),
      Book('Selena', 'Tere Liye', 'Rp 85.000',
          'assets/images/selena.jpg', 4.8, 372, 270, 'https://shopee.co.id/Bulan-New-Cover-(Tere-Liye)-i.63842097.1136742058', 'SELENA dan NEBULA adalah buku ke-8 dan ke-9 yang menceritakan siapa orangtua Raib dalam serial petualangan dunia paralel. Dua buku ini sebaiknya dibaca berurutan. Kedua buku ini juga bercerita tentang Akademi Bayangan Tingkat Tinggi, sekolah terbaik di seluruh Klan Bulan. Tentang persahabatan tiga mahasiswa, yang diam-diam memiliki rencana bertualang ke tempat-tempat jauh. Tapi petualangan itu berakhir buruk, saat persahabatan mereka diuji dengan rasa suka, egoisme, dan pengkhianatan. Ada banyak karakter baru, tempat-tempat baru, juga sejarah dunia paralel yang diungkap. Di dua buku ini kalian akan berkenalan dengan salah satu karakter paling kuat di dunia paralel sejauh ini. Tapi itu jika kalian bisa menebaknya. Dua buku ini bukan akhir. Justru awal terbukanya kembali portal menuju Klan Aldebaran.'),
      Book('Spy X Family 01', 'Endo Tatsuya', 'Rp 45.000',
          'assets/images/spy01.jpg', 5.0, 212, 270, 'https://www.lazada.co.id/products/spy-x-family-01-i5121692860-s9520844685.html', 'Keluarga Forger punya rahasia. Sang ayah adalah agen rahasia terhebat. Sang ibu adalah pembunuh. Sang anak memiliki kemampuan untuk membaca pikiran. Meski mereka hanya keluarga palsu yang saling menyimpan rahasia dari satu sama lain, ternyata ada kehangatan di sana.'),
      Book('Chicken Soup For The Soul: Kekuatan Berpikir Positif', 'Jack Canfield, Amy Newmark & Claire Cook', 'Rp 98.000',
          'assets/images/pos.jpg', 4.9, 494, 270, 'https://www.tokopedia.com/gramedia-store/chicken-soup-for-the-soul-kekuatan-berpikir-positif', 'Berterima kasih atau bersyukur merupakan rahasia hidup yang bahagia dan berhasil. Daftar konsekuensi yang mengikuti rasa syukur begitu panjang dan menakjubkan, seperti usia yang lebih panjang, semangat dan optimisme yang lebih tinggi, sistem imun yang lebih tinggi, dan toleransi yang lebih besar. Itulah ajaibnya rasa syukur. Kisah-kisah dalam buku ini semuanya memperlihatkan saat-saat penuh rasa syukur.Ada yang luar biasa—tetapi sebagian besar merupakan bagian dari hidup sehari-hari. Sesungguhnya hal-hal kecillah yang berperan penting. Kita akan secara alami terbiasa “memandang segala sesuatu dari sisi terangnya.” Mensyukuri berkat yang kita peroleh juga membuat suasana hati semain baik, yang dapat mengurangi dampak dari stres, dan menghadirkan kehidupan yang lebih bahagia dan bermakna. Itulah ajaibnya rasa syukur.'),
    ];
  }

  static List<Book> generateTeknologi() {
    return[
      Book('7 in 1 Pemograman Web untuk Pemula', 'Rohi Abdulloh', 'Rp 74.800',
          'assets/images/pemula.jpg', 5.0, 338, 270, 'https://www.tokopedia.com/gramedia-store/7-in-1-pemrograman-web-untuk-pemula','Teknologi pemrograman web berkembang begitu cepat. Bagi pemula, tentu akan sangat tertinggal jika tidak cepat mengejarnya. Buku ini membahas 7 materi utama dalam mempelajari pemrograman web. Ketujuh bahasan ini akan sangat membantu pemula yang ingin menjadi web programmer dalam waktu yang singkat. Pembahasan dimulai dari pengetahuan dasar tentang pemrograman web, dilanjutkan dengan pembahasan 7 materi pemrograman web satu per satu disertai dengan contoh skrip beserta hasilnya.'),
      Book('Android Application Development for Rookies with Database', 'Nadia Firly', 'Rp 70.000',
          'assets/images/rookies.jpg', 4.9, 264, 270, 'https://www.lazada.co.id/products/buku-android-application-development-for-rookies-with-database-i640790397-s890124392.html', 'Sudah tidak zaman lagi kebanyakan teori. Buku Android Application Development for Rookies with Database akan memandu Anda dalam melakukan berbagai implementasi program pada Android Studio. Dengan silabus yang tepat dan bahasa yang mudah dipahami, kini siapa pun bisa menjadi developer Android. Ayo bangun dan jadilah pemain! Sudah saatnya Anda membuat sebuah aplikasi hingga dapat mengunggahnya ke Google Play. Terlebih, proyek yang ada pada buku ini telah menggunakan 2 jenis database, yaitu SQLite dan Firebase sekaligus.'),
      Book('Desain Web bagi Pemula', 'Candra Surya & Miftahul Jannah', 'Rp 70.000',
          'assets/images/desain.jpg', 4.9, 292, 270, 'https://www.tokopedia.com/gramedia-store/desain-web-bagi-pemula', 'Buku ini membahas cara merancang web menggunakan bahasa HTML dan CSS, menitikberatkan pada study kasus serta contoh penggunaan setiap kode HTML dan CSS. Dan masih banyak lagi pembahasan lainnya yang tidak kalah penting untuk dipelajari.'),
      Book('Membuat Sendiri Aplikasi Augmented Reality', 'Ani Ismayani', 'Rp 60.000',
          'assets/images/ar.jpg', 4.5, 228, 270, 'https://www.tokopedia.com/gramedia-store/membuat-sendiri-aplikasi-augmented-reality', 'Penggunaan AR sudah sangat umum, mulai dari game sampai dunia pendidikan dan pembelajaran. Tersedianya aplikasi gratis seperti Unity dan Vuforia memungkinkan pembuatan aplikasi berbasis AR tidak sulit dilakukan oleh siapa saja. Buku ini secara umum menjelaskan bagaimana pemanfaatan AR dalam pembelajaran. Di sini diberikan contoh pembuatan AR dalam bentuk bangun ruang sederhana, harimau 3D, dan video player atau animasi. Meskipun secara umum ditujukan untuk pembelajaran, langkah-langkah yang dijelaskan di sini tentu saja dapat diterapkan untuk aplikasi lainnya, misalnya membuat game 3D. Semua tergantung kreativitas Anda.'),
      Book('Otodidak Adobe After Effects dan Adobe Premiere', 'Jubilee Enterprise', 'Rp 74.000',
          'assets/images/after.jpg', 4.8, 284, 270, 'https://www.lazada.co.id/products/otodidak-adobe-after-effects-dan-adobe-premiere-i3057640443-s5426786772.html', 'Adobe Premiere Pro CC 2019 yang dibahas di dalam buku ini merupakan software paling bagus untuk mengedit video. Maka dari itu, pembahasan dasar-dasar video editing seperti mengimpor footage, mengelola clip, mengatur sequence dan timeline, membuat marker, menghadirkan efek-efek khusus, menulis teks, mengontrol audio, dan lain sebagainya, dibahas secara singkat tapi jelas.'),
      Book('Paket Lengkap CorelDraw dan Photoshop', 'Alfa Hartoko', 'Rp 80.000',
          'assets/images/corel.jpg', 4.8, 304, 270, 'https://www.tokopedia.com/gramedia-store/paket-lengkap-coreldraw-dan-photoshop', 'Buku ini bisa menjadi solusi bagi Anda yang ingin mendapatkan pembahasan lengkap mengenai kinerja dua software grafis sekaligus, yaitu CorelDraw dan Photoshop. Secara komplet, buku ini mengulas seluruh langkah-langkah penggunaan fasilitas yang ada di CorelDraw dan Photoshop mulai dari dasar hingga Anda mampu untuk membuat kreasi dari kedua software grafis tersebut. Beragam fasilitas dalam CorelDraw dan Photoshop seperti penggunaan tool, pewarnaan, pencahayaan, pembuatan teks, teknik koreksi, serta pembuatan desain secara tuntas bisa didapat di buku ini. Editing Foto untuk menghasilkan efek yang sangat menarik diulas dalam buku ini secara gamblang dan padat. Bagi Anda yang ingin secara langsung masuk dunia kerja dan mendapatkan penghasilan dari software grafis juga bisa karena buku ini langsung mengajarkan cara membuat desain yang bernilai jual, seperti kreasi teks dan pengolahan, serta editing foto. Jadi, Anda tidak hanya diajari teori seputar penggunaan CorelDraw dan Photoshop namun juga langsung pada penerapannya.'),
    ];
  }

  static List<Book> generateNovel(){
    return[
      Book('Fish in The Water', 'Lee Chanhyuk', 'Rp 63.000',
          'assets/images/fish.jpg', 4.9, 176, 270, 'https://www.tokopedia.com/gramedia-store/fish-in-the-water', 'Fish in the Water bertutur tentang kisah intens yang menjungkirbalikkan imajinasi, dengan komposisi kuat untuk menunjukkan pertentangan antara ambisi dan ketakutan,kebebasan dan kendali, kebahagiaan dari cinta dan luka dari kehilangan, serta arti kehidupan, terkadang dengan tenangdan terkadang dengan fantastis.'),
      Book('To Heal Is To Let Go', 'Adi K.', 'Rp 82.000',
          'assets/images/letgo.jpg', 4.7, 196, 270, 'https://www.tokopedia.com/gramedia-store/to-heal-is-to-let-go-to-heal-2-hc', 'Hidup adalah soal menerima dan melepaskan. Melepaskan sesuatu yang dulu pernah menjadi bagian terbaik dari hidupmu. Melepaskan beban dan masa lalu yang suram dan menyedihkan. Melepaskan kebencian dan dendam yang selama ini menghantui pikiranmu. Namun pada kenyataannya melepaskan tidak semudah yang diucapkan. Kadang sulit, bahkan sangat sulit. Kau harus benar-benar bisa melupakan dan merelakan untuk dapat melepaskan dengan sesungguh-sungguhnya. “To Heal is To Let Go” adalah buku self-motivation untuk remaja hingga dewasa yang sedang dilanda masalah dan kehilangan rasa percaya diri. Dengan nasihat-nasihat yang pendek, lugas, dan langsung, buku ini dapat menjadi inspirasi, penyemangat, serta penenang hati.'),
      Book('Serangkai', 'Valerie Patkar', 'Rp 99.000',
          'assets/images/serangkai.jpg', 5.0, 404, 270, 'https://shopee.co.id/Serangkai-(karya-Valerie-Patkar)-i.63842097.8803955567', '“Tetapi bukan masalah kalau kita nggak selalu bisa berani, Deverra. Karena manusia bukan hanya lahir dari tulang, melainkan juga hati. Semesta bukan hanya menciptakan tubuh, melainkan juga rasa. Dan waktu bukan hanya tentang hari esok, melainkan juga kemarin.”. Kecelakaan di perhelatan Grand Prix Formula 1 membawa Kai Deverra yang masih merayakan penyesalan ditinggal kekasih lamanya kepada Karina Maladivas Nota yang baru pulang dari kesepian. Setangkai cerita kesedihan Deverra menyatu dengan setangkai cerita kesunyian Divas, membentuk serangkai cerita untuk mengenang yang hilang. Tentang Deverra, Dari Divas, untuk Zacchio.'),
      Book('Percakapan Paling Panjang Perihal Pulang Pergi', 'Theoresia Rumthe & Weslly Johannes', 'Rp 50.000',
          'assets/images/pergi.jpg', 4.9, 124, 270, 'https://www.tokopedia.com/gramedia-store/percakapan-paling-panjang-perihal-pulang-pergi', 'Bukan jalan yang membawa manusia sampai ke tujuan, melainkan sepasang kaki yang kuat.'),
      Book('Tenang, Semua akan Baik-Baik Saja', 'Jedit', 'Rp 110.000',
          'assets/images/baik.jpg', 4.8, 244, 270, 'https://www.tokopedia.com/gramedia-store/tenang-semua-akan-baik-baik-saja', 'Aku menyiapkan kisah-kisah tentang perjalanan mencari kenangan indah, penantian terhadap sinar mentari pagi. Kisah yang akan menemani saat terjaga di tengah malam dan kisah yang akan diceritakan saat malam berbintang. Aku sangat senang jika kita bisa pergi ke semesta kecilku. Di sana, kita bisa berbagi cerita bersama. Mampirlah, aku selalu menunggu di sini.'),
      Book('Selena', 'Tere Liye', 'Rp 85.000',
          'assets/images/selena.jpg', 4.8, 372, 270, 'https://shopee.co.id/Bulan-New-Cover-(Tere-Liye)-i.63842097.1136742058', 'SELENA dan NEBULA adalah buku ke-8 dan ke-9 yang menceritakan siapa orangtua Raib dalam serial petualangan dunia paralel. Dua buku ini sebaiknya dibaca berurutan. Kedua buku ini juga bercerita tentang Akademi Bayangan Tingkat Tinggi, sekolah terbaik di seluruh Klan Bulan. Tentang persahabatan tiga mahasiswa, yang diam-diam memiliki rencana bertualang ke tempat-tempat jauh. Tapi petualangan itu berakhir buruk, saat persahabatan mereka diuji dengan rasa suka, egoisme, dan pengkhianatan. Ada banyak karakter baru, tempat-tempat baru, juga sejarah dunia paralel yang diungkap. Di dua buku ini kalian akan berkenalan dengan salah satu karakter paling kuat di dunia paralel sejauh ini. Tapi itu jika kalian bisa menebaknya. Dua buku ini bukan akhir. Justru awal terbukanya kembali portal menuju Klan Aldebaran.'),
    ];
  }

  static List<Book> generateKomik(){
    return[
      Book('Jujutsu Kaisen 01', 'Gege Akutami', 'Rp 40.000',
          'assets/images/jujutsu.jpg', 5.0, 200, 270, 'https://www.lazada.co.id/products/jujutsu-kaisen-01-i4715126888-s8483282113.html', 'Yuji Itadori seorang murid SMA dengan kemampuan atletik yang luar biasa. Kesehariannya adalah menjenguk kakeknya yang terbaring di rumah sakit. Suatu hari, segel "objek terkutuk" yang berada di sekolahnya terlepas, monster-monster pun mulai bermunculan. Yuji menyusup ke dalam gedung sekolah demi menolong senior di klubnya, akan tetapi...!?'),
      Book('Demon Slayer: Kimetsu No Yaiba 05', 'Koyoharu Gotouge', 'Rp 40.000',
          'assets/images/demon.jpg', 4.9, 192, 270, 'https://www.lazada.co.id/products/demon-slayer-kimetsu-no-yaiba-05-i4905384747-s9034450569.html', 'Tanjiro Dkk. akhirnya beranjak menuju Gunung Natagumo dan bertarung begitu alot melawan keluarga iblis laba-laba penghuni gunung tersebut! Zenitsu terkena racun yang akan mengubahnya menjadi laba-laba, Inosuke dan Tanjiro menjadi bulan-bulanan iblis raksasa yang berperan sebagai ayah. Ujung pertarungan mereka belum tampak... Di tengah keputusasaan itu, adakah yang bergerak menyusul mereka di belakang!?'),
      Book('Spy X Family 01', 'Endo Tatsuya', 'Rp 45.000',
          'assets/images/spy01.jpg', 5.0, 212, 270, 'https://www.lazada.co.id/products/spy-x-family-01-i5121692860-s9520844685.html', 'Keluarga Forger punya rahasia. Sang ayah adalah agen rahasia terhebat. Sang ibu adalah pembunuh. Sang anak memiliki kemampuan untuk membaca pikiran. Meski mereka hanya keluarga palsu yang saling menyimpan rahasia dari satu sama lain, ternyata ada kehangatan di sana.'),
      Book('Haikyu!!: Fly High! Volleyball! 24', 'Haruichi Furudate', 'Rp 28.000',
          'assets/images/haikyu.jpeg', 5.0, 216, 270, 'https://www.lazada.co.id/products/haikyu-fly-high-volleyball-21-i3057280513-s5426416273.html', 'Pertandingan melawan Shiratorizawa telah sampai pada set kelima. Cedera yang dialami Tsukishima menyebabkan kekosongan pada pilar pertahanan Karasuno, tapi mereka terus berjuang dengan tekad kuat untuk merebut angka! Pertarungan sengit yang menguras stamina ini akhirnya sampai pada babak terakhir. Siapakah yang akan mendapatkan predikat wakil prefektur?'),
      Book('Detektif Conan The Movie: The Raven Chaser 01', 'Aoyama Gosho', 'Rp 40.000',
          'assets/images/conan.jpg', 5.0, 192, 270, 'https://www.lazada.co.id/products/detektif-conan-the-movie-the-raven-chaser-01-i5132828577-s9543452084.html', 'Terjadi pembunuhan berantai di mana pelaku meninggalkan sekeping pion mahjong di tkp. Tetapi, tampaknya ini lebih pelik dari sekedar pembunuhan, karena bayang-bayang organisasi hitam mulai muncul...!?'),
      Book('One Piece 90', 'Eiichiro Oda', 'Rp 25.000',
          'assets/images/one.jpg', 4.9, 200, 270, 'https://www.lazada.co.id/products/one-piece-90-i1561334464-s2986694688.html', 'Bendera bajak laut Kelompok Topi Jerami mengambang di lautan... Apa mereka telah dikalahkan oleh gempuran kelompok Mom yang tak terhentikan!? Bagian WCI yang menegangkan mencapai akhir!! Dan cerita memasuki babak Levely di mana berbagai tujuan bercampur aduk!! Simak inilah kisah petualangan di lautan, One Piece!!'),
    ];
  }

  static List<Book> generateSelfImprovement(){
    return[
      Book('Sebuah Seni Untuk Bersikap Bodo Amat', 'Mark Manson', 'Rp 67.000',
          'assets/images/bodo.jpg', 4.9, 224, 270, 'https://www.tokopedia.com/gramedia-store/sebuah-seni-untuk-bersikap-bodo-amat', 'Dalam buku pengembangan diri yang mewakili generasi ini, seorang bloger superstar menunjukkan pada kita baa kunci untuk menjadi orang yang lebih kuat, lebih bahagia adalah dengan mengerjakan segala tantangan dengan lebih baik dan berhenti memaksa diri untuk menjadi "positif" di setiap saat. Selama beberapa tahun belakangan, Mark Manson-melalui blognya yang sangat populer-telah membantu mengoreksi harapan-harapan delusional kita, baik mengenai diri kita sendiri maupun dunia. Ia kini menuangkan buah pikirnya yang keren itu di dalam buku hebat ini. Manson melontarkan argumen baa manusia tak sempurna dan terbatas. Begini tulisnya, "tidak semua orang bisa menjadi luar biasa-ada para pemenang dan pecundang di masyarakat, dan beberapa di antaranya tidak adil dan bukan akibat kesalahan Anda." Manson mengajak kita untuk mengerti batasan-batasan diri dan menerimanya-baginya, ini adalah sumber kekuatan yang paling nyata. Tepat saat kita mampu mengakrabi ketakutan, kegagalan, dan ketidakpastian-tepat saat kita berhenti melarikan diri dan mengelak, dan mulai menghadapi kenyataan-kenyataan yang menyakitkan-saat itulah kita bisa mulai menemukan keberanian dan kepercayaan diri yang selama ini kita cari dengan sekuat tenaga. "Dalam hidup ini, kita hanya punya kepedulian dalam jumlah yang terbatas. Makanya, Anda harus bijaksana dalam menentukan kepedulian Anda." Manson menciptakan momen perbincangan yang serius dan mendalam, dibungkus dengan cerita-cerita yang menghibur dan "kekinian", serta humor yang cadas. Buku ini merupakan tamparan di wajah yang menyegarkan untuk kita semua, supaya kita bisa mulai menjalani kehidupan yang lebih memuaskan, dan apa adanya.'),
      Book('The Power of Habit', 'Charles Duhigg', 'Rp 90.000',
          'assets/images/habit.jpg', 4.9, 371, 270, 'https://www.lazada.co.id/products/the-power-of-habit-i592650472-s836348894.html', '"Few (books) become essential manuals for businesa and living. The Power of Habit is an axception. Charles Duhigg not only explains how habits are formed but how to kock bad anes and hang on to the good"- Financial Times"You wll never look at yourself, your organization, or your world quite the same way." - DANIEL H. PINK, bestselling author of Drive and A Whole New Mind'),
      Book('You Do You: Discovering Life through Experiments & Self Awareness', 'writer', 'Rp 128.000',
          'assets/images/you.jpg', 5.0, 252, 270, 'https://www.tokopedia.com/gramedia-store/you-do-you-discovering-life-through-experiments-self-awareness', '“Mas, gimana kalau passion gue belum menghasilkan?” “Mas, apakah lebih baik jadi generalis atau spesialis?” “Mas, gue pengin bisa ganti haluan karier di bidang yang lain, bisakah? “Mas, gue lagi di tengah-tengah quarter-life crisis. Help me.” “Mas, gue bingung ikigai gue apa.” “Mas, emang di usia 30 nanti, secara finansial gue udah mesti punya apa aja?” “Mas, berbagi dong proses lo menuju ke Rp1M pertama.” I feel you. Gue juga pernah mengalami keresahan yang sama. Faktanya, satu dekade pertama dalam perjalanan karier gue dihabiskan untuk bereksperimen dengan sembilan macam role yang berbeda, sampai akhirnya gue menemukan ikigai. Sales, petugas lelang, operator alat berat, travel blogger, food photographer, penyanyi, social media manager, product manager di sebuah tech startup, sampai pengusaha pernah gue jalani. Menariknya, semua kegalauan dan pencarian itu mulai terjawab dengan sendirinya ketika gue bisa menjawab pertanyaan: “Who are you?” Ketika gue mengenal diri sendiri, maka pada titik itulah gue menemukan jawaban bahwa “your life (career, business, relationship, and finance) should be an extension of who you are”. Buku ini nggak ngasih jawaban langsung, tapi ngebantu merefleksi diri, melihat ke dalam, mengurai situasi, supaya lo bisa menemukan sendiri jawaban, kapan pun lo bertemu dengan persimpangan. Let`s begin the journey of finding yourself.'),
      Book('Semoga Kamu Baik-Baik Saja', 'Marcella Viona Legoh', 'Rp 85.000',
          'assets/images/baikbaik.jpg', 5.0, 128, 270, 'https://www.tokopedia.com/gramedia-store/semoga-kamu-baik-baik-saja-spesial-offer', 'Bahagia, capek,, galau, stres, bangga, sedih, kasmaran, takut, semangat, kesal, panik, pusing, penuh harapan, kecewa. Hidup pasti ada naik turunnya. Tapi dalam keadaan baik maupun buruk, selalu ada pesan-pesan kehidupan yang bisa membantu kita buat jadi lebih baik. Buku ini adalah pengingat bahwa apa yang sedang kita alami, hidup tetap bisa dinikmati, mumpung kita masih disini!'),
      Book('Buku Antimalas dan Suka Menunda', 'Eya Agency', 'Rp 120.000',
          'assets/images/suka.jpg', 5.0, 250, 270, 'https://www.tokopedia.com/gramedia-store/buku-antimalas-dan-suka-menunda', 'Pernahkah kamu merasa sudah berjuang keras tetapi masih dianggap malas? Ada yang menghakimi kamu malas karena mendapat nilai jelek, padahal kamu sudah berlajar mati-matian. Ada yang menghakimi kamu malas karena target kerja tidak tercapai, padahal kamu sudah berhari-hari lembur untuk menyelesaikannya. Atau, kamu memang lebih suka rebahan? Nah, sebenarnya apakah kamu memang benar malas, atau ada hal lain yang membuatmu terlihat malas? Coba cari tahu melalui buku ini dan temukan solusinya. Karena sesungguhnya, ada kemalasan yang disebabkan oleh masalah emosi, sehingga perlu dicari tahu akar permasalahannya untuk membasmi rasa malas tersebut.'),
      Book('Chicken Soup For The Soul: Kekuatan Berpikir Positif', ' Jack Canfield, Amy Newmark & Claire Cook', 'Rp 98.000',
          'assets/images/pos.jpg', 4.9, 494, 270, 'https://www.tokopedia.com/gramedia-store/chicken-soup-for-the-soul-kekuatan-berpikir-positif', 'Berterima kasih atau bersyukur merupakan rahasia hidup yang bahagia dan berhasil. Daftar konsekuensi yang mengikuti rasa syukur begitu panjang dan menakjubkan, seperti usia yang lebih panjang, semangat dan optimisme yang lebih tinggi, sistem imun yang lebih tinggi, dan toleransi yang lebih besar. Itulah ajaibnya rasa syukur. Kisah-kisah dalam buku ini semuanya memperlihatkan saat-saat penuh rasa syukur.Ada yang luar biasa—tetapi sebagian besar merupakan bagian dari hidup sehari-hari. Sesungguhnya hal-hal kecillah yang berperan penting. Kita akan secara alami terbiasa “memandang segala sesuatu dari sisi terangnya.” Mensyukuri berkat yang kita peroleh juga membuat suasana hati semain baik, yang dapat mengurangi dampak dari stres, dan menghadirkan kehidupan yang lebih bahagia dan bermakna. Itulah ajaibnya rasa syukur.'),
    ];
  }
}